
!********************************************************************************************************************************************
!	!PROGRAMME TO ANALYSE 2-D FRAMES CONSIDERING THE LOADS AND ALL THE OTHER EXTERNAL EFFECTS.
!	!BY FARBOUD KHATAMI AND EHSAN TORKAMAN
!	!YEAR 1392-93 / 2013
!********************************************************************************************************************************************


	PROGRAM FRAME_ANALYSIS							!MAIN PROGRAMME

!VARIABLE DECLERATIONS-----------------------------------------------------------------------------------------------------------------------

	IMPLICIT REAL (A-Z)
	 
	INTEGER I,J,XX,YY,II,QQ	,NUMBER					!COUNTERS
	INTEGER NUM_NODE								!THE NUMBER OF NODES
	INTEGER NUM_ELEM								!THE NUMBER OF ELEMENTS
	INTEGER NUM_SUP									!THE NUMBER OF SUPPORTED NODES
	INTEGER NUM_TEMP								!THE NUMBER OF ELEMENTS WITH TEMPERATURE EFFECT
	INTEGER NUM_DEF									!THE NUMBER OF SUPPORTS WITH A DEFLECTION
	INTEGER SUPPORT									!DEFINES THE TYPE OF SUPPORT
	INTEGER NUM_LOAD								!THE NUMBER OF LOADED ELEMENTS
	INTEGER LD										!DEFINES THE TYPE OF LOAD ON THE MEMBERS
	INTEGER COUNT									!THE NUMBER OF FREE DEGREES OF FREEDOM
	INTEGER COUNTF									!FREE DEGREES OF FREEDOM COUNTER
	INTEGER COUNTS									!SECURED DEGREES OF FREEDOM COUNTER
	REAL :: AREA, E, MI							!A, E, AND I OF A MEMBER
	REAL , ALLOCATABLE, DIMENSION(:)::  LOAD		!X_LOAD, Y_LOAD, AND MOMENT OF EACH NODE RESPECTIVELY 
	REAL , ALLOCATABLE, DIMENSION(:)::  FORCE		!X_FORCE, Y_FORCE, AND MOMENT OF EACH NODE RESPECTIVELY ==> THE ANSWER
	REAL , ALLOCATABLE, DIMENSION(:)::  FEM		!FIXED END X_FORCE,Y_FORCE AND MOMENT
	REAL , ALLOCATABLE, DIMENSION(:)::  F_EL	     !NEWWWWWWWWWW
	REAL , ALLOCATABLE, DIMENSION(:,:)::FEM_EL     !NEWWWWWWWWWW
	REAL , ALLOCATABLE, DIMENSION(:)::  SCU        !NEWWWWWWWWWW
	REAL , ALLOCATABLE, DIMENSION(:)::  DELTA_EL   !NWWWWWWWWWWW
	REAL , ALLOCATABLE, DIMENSION(:)::  FEMTEMP	!A TEMPORARILY FEM
	REAL , ALLOCATABLE, DIMENSION(:)::  DISP		!X_DISPLACEMENT, Y_DISPLACEMENT, AND ROTATION OF EACH NODE RESPECTIVELY 
	REAL , ALLOCATABLE, DIMENSION(:)::  DOF		!NODES DEGREE OF FREEDOM IN THE X, Y, AND MOMENT DIRECTION RESPECTIVELY
	REAL , ALLOCATABLE, DIMENSION(:,:)::NODE		!NODE CO-ORDINATES (X,Y)
	REAL , ALLOCATABLE, DIMENSION(:,:)::NODENUM	!ELEMENT11 & ELEMENT12
	REAL , ALLOCATABLE, DIMENSION(:,:)::ELEMENT	!ELEMENT CO-ORDINATES AND DATA (ELEMENT_NUMBER-X1-Y1-X2-Y2-L-THETHA(RAD)-E-I-A-NODE1-NODE2-NODE1X-NODE1Y-NODE2X-NODE2Y)
	REAL , ALLOCATABLE, DIMENSION(:,:)::ELEMENT_BACKUP !NEWWWWWWWWWWWWWWWW
	REAL , ALLOCATABLE, DIMENSION(:,:)::KL		!LOCAL STIFFNES MATRIX OF AN ELEMENT
	REAL , ALLOCATABLE, DIMENSION(:,:)::KG		!GLOBAL STIFFNES MATRIX OF AN ELEMENT
	REAL , ALLOCATABLE, DIMENSION(:,:)::K			!GLOBAL STIFFNES MATRIX OF THE STRUCTURE
	REAL , ALLOCATABLE, DIMENSION(:,:)::T			!TRANSPOSITION MATRIX
	REAL , ALLOCATABLE, DIMENSION(:,:)::KF		!FREE STIFFNESS MATRIX
	REAL , ALLOCATABLE, DIMENSION(:,:)::KFINV		!INVERSE OF FREE STIFFNESS MATRIX
	REAL , ALLOCATABLE, DIMENSION(:)::  FEMF		!FREE FEM
	REAL , ALLOCATABLE, DIMENSION(:,:)::KFS		!FREE-SECURED SFIFFNESS MATRIX
	REAL , ALLOCATABLE, DIMENSION(:)  ::DELTAF	!DELTA F
	REAL , ALLOCATABLE, DIMENSION(:)  ::DELTAS	!DELTA S
	REAL , ALLOCATABLE, DIMENSION(:,:)::S_DEF 	!A SET OF DEFLECTED SUPPORTS, THEIR DOF NUMBER AND THEIR MAGNITUDE
	CHARACTER (LEN=1)::VERIFY						!Y OR N 

	OPEN(3,FILE="OUTPUT.TXT")						!THE OUTPUT.TXT FILE
!NODES---------------------------------------------------------------------------------------------------------------------------------------
	WRITE (*,104) "ENTER THE NUMBER OF NODES: "
	READ (*,*),NUM_NODE								!TOTAL NUMBER OF NODES
	ALLOCATE (NODE(NUM_NODE,2),DELTA_EL(6),F_EL(6),SCU(6),LOAD(3*NUM_NODE),FORCE(3*NUM_NODE),DISP(3*NUM_NODE),DOF(3*NUM_NODE),FEM(3*NUM_NODE),FEMTEMP(3*NUM_NODE))
	ALLOCATE (KL(6,6),KG(6,6),K(3*NUM_NODE,3*NUM_NODE),T(6,6))
	K=0
	KL=0
	KG=0
	T=0
	NODE=0; LOAD=0; FORCE=0; DISP=0; FEM=0; FEMTEMP=0
	DOF=1								!SO THAT THE DEGREES OF FREEDOM NOT BE ZERO BY DEFAULT
	DO I=1,NUM_NODE
		WRITE (*,103) "NODE NUMBER", I,":"
		WRITE (3,103) "NODE NUMBER", I,":"
		WRITE (*,100) "X CO-ORDINATE: (m) "
		WRITE (3,100) "X CO-ORDINATE: (m) "
		READ (*,*) NODE(I,1)
		WRITE (3,118) NODE(I,1)
		WRITE (*,100) "Y CO-ORDINATE: (m) "
		WRITE (3,100) "Y CO-ORDINATE: (m) "
		READ (*,*) NODE(I,2)
		WRITE (3,118) NODE(I,2)
	END DO
		WRITE (3,*)
!ELEMENTS------------------------------------------------------------------------------------------------------------------------------------
	WRITE (*,104) "ENTER THE NUMBER OF ELEMENTS: "
	READ (*,*) NUM_ELEM																		!TOTAL NUMBER OF ELEMENTS
	ALLOCATE (ELEMENT(NUM_ELEM,18),ELEMENT_BACKUP(NUM_ELEM,18),FEM_EL(6,NUM_ELEM))
	ELEMENT=0
	DO I=1,NUM_ELEM
		ELEMENT(I,1)=I																		!THE NUMBER OF ELEMENT
		WRITE (*,105)"ELEMENT NUMBER",I,":"
		WRITE (*,100)"THE NUMBER OF NODE AT THE FIRST POINT OF MEMBER : "
		READ (*,*) ELEMENT (I,11)															!NODE1
		WRITE (*,100)"THE NUMBER OF NODE AT THE SECOND POINT OF MEMBER: "
		READ (*,*) ELEMENT (I,12)															!NODE2
		ELEMENT(I,2)=NODE(ELEMENT (I,11),1)													!X1
		ELEMENT(I,3)=NODE(ELEMENT (I,11),2)													!Y1	
		ELEMENT(I,4)=NODE(ELEMENT (I,12),1)													!X2
		ELEMENT(I,5)=NODE(ELEMENT (I,12),2)													!Y2
		ELEMENT(I,6)=SQRT((ELEMENT(I,3)-ELEMENT(I,5))**2+(ELEMENT(I,2)-ELEMENT(I,4))**2)	!LENGHT OF MEMBER																	
		ELEMENT(I,7)=ATAN((ELEMENT(I,5)-ELEMENT(I,3))/(ELEMENT(I,4)-ELEMENT(I,2)))			!THETA (RAD)																
		ELEMENT (I,13)=NODE(ELEMENT (I,11),1)												!NODE 1 X
		ELEMENT (I,14)=NODE(ELEMENT (I,11),2)												!NODE 1 Y
		ELEMENT (I,15)=NODE(ELEMENT (I,12),1)												!NODE 2 X
		ELEMENT (I,16)=NODE(ELEMENT (I,12),2)												!NODE 2 Y
		ELEMENT (I,17)=(ELEMENT(I,4)-ELEMENT(I,2))/ELEMENT(I,6)										!COS THETHA		
		ELEMENT (I,18)=(ELEMENT(I,5)-ELEMENT(I,3))/ELEMENT(I,6)										!SIN THETHA
	END DO
!ELEMENTS AREA-------------------------------------------------------------------------------------------------------------------------------
	NUM=NUM_ELEM
	DO I=1,NUM
		WRITE (*,103) "ELEMENT NUMBER", I,":"
		NUMBER=I
		WRITE (*,100) "CROSS-SECTION AREA? (mm^2) "
		READ (*,*) AREA
		ELEMENT(NUMBER,10)=AREA
	END DO
!ELEMENTS MOMENT OF INERTIA------------------------------------------------------------------------------------------------------------------
	NUM=NUM_ELEM
	DO I=1,NUM
		WRITE (*,103) "ELEMENT NUMBER", I,":"
		NUMBER=I
		WRITE (*,100) "MOMENT OF INERTIA? (mm^4) "
		READ (*,*) MI
		ELEMENT(NUMBER,9)=MI
	END DO
!ELEMENTS MODULUS OF ELASTICITY--------------------------------------------------------------------------------------------------------------
	NUM=NUM_ELEM
	DO I=1,NUM
		WRITE (*,103) "ELEMENT NUMBER", I,":"
		NUMBER=I
		WRITE (*,100) "MODULUS OF ELASTICITY? (MPa) "
		READ (*,*) E
		ELEMENT(NUMBER,8)=E
	END DO
!SECTION PROPERTIES OUTPUT-------------------------------------------------------------------------------------------------------------------
	WRITE (3,103) "THE MEMBERS SECTION PROPERTIES ARE AS FOLLOWS:"								!SECTION PROPERTIES VERIFICATION
	WRITE (3,106) "NO.","E (MPa)","I (mm^4)","   A (mm^2)"
	WRITE (3,101) "---------------------------------------------------------------------------"
	DO I=1,NUM_ELEM
		WRITE (3,107) ELEMENT(I,1), (ELEMENT(I,J),J=8,10)
	END DO
	WRITE (3,*)
!SUPPORTS------------------------------------------------------------------------------------------------------------------------------------
	WRITE (*,103) "SUPPORT TYPES:"
	WRITE (*,*) "1: PIN" , "   2: ROLLER" , "   3: FIXED" , "   4: GUIDED" 
	WRITE (*,*) "----------------------------------------"
	WRITE (*,104) "ENTER THE NUMBER OF SUPPORTED NODES: "
	READ (*,*) NUM_SUP
	DO I=1,NUM_SUP
		WRITE (*,104) "THE NUMBER OF NODE: "
		READ (*,*) N
88		WRITE (*,100) "TYPE OF SUPPORT:"
		READ (*,*) SUPPORT
		SELECT CASE (SUPPORT)
			CASE (1)
				DOF(3*N-2)=0								!X DOF
				DOF(3*N-1)=0								!Y DOF
				DOF(3*N)=1									!ROTATION DOF
			CASE (2)
31				WRITE (*,100) "VERTICAL OR HORIZONTAL? (V/H)"
				READ (*,*) VERIFY
				IF (VERIFY=="V".OR.VERIFY=="v") THEN
					DOF(3*N-2)=0								!X DOF
					DOF(3*N-1)=1								!Y DOF
					DOF(3*N)=1									!ROTATION DOF
				ELSE IF (VERIFY=="H".OR.VERIFY=="h") THEN
					DOF(3*N-2)=1								!X DOF
					DOF(3*N-1)=0								!Y DOF
					DOF(3*N)=1									!ROTATION DOF
				ELSE
					WRITE(*,101), "TYPING MISTAKE MATE! TRY AGAIN."
					GOTO 31		
				END IF
			CASE (3)
				DOF(3*N-2)=0								!X DOF
				DOF(3*N-1)=0								!Y DOF
				DOF(3*N)=0									!ROTATION DOF
			CASE (4)
32				WRITE (*,100) "VERTICAL OR HORIZONTAL? (V/H)"
				READ (*,*) VERIFY
				IF (VERIFY=="V".OR.VERIFY=="v") THEN
					DOF(3*N-2)=0								!X DOF
					DOF(3*N-1)=1								!Y DOF
					DOF(3*N)=0									!ROTATION DOF
				ELSE IF (VERIFY=="H".OR.VERIFY=="h") THEN
					DOF(3*N-2)=1								!X DOF
					DOF(3*N-1)=0								!Y DOF
					DOF(3*N)=0									!ROTATION DOF
				ELSE
					GOTO 32
				END IF				
		CASE DEFAULT
			GOTO 88
		END SELECT
	END DO
!CALCULATIONS1--------------------------------------------------------------------------------------------------------------------------------
  ELEMENT_BACKUP=ELEMENT	
	K=0
	DO I=1,NUM_ELEM
		KG=0
	CALL KGELOBAL(ELEMENT(I,8),ELEMENT(I,9),ELEMENT(I,10),ELEMENT(I,6)*1000,COS(ELEMENT(I,7)),SIN(ELEMENT(I,7)),KG)
		!ASSEMBLAGE OF GLOBAL STIFFNESS MATRIX
		!FIRST COLUMN
		K(3*ELEMENT(I,11)-2,3*ELEMENT(I,11)-2)=K(3*ELEMENT(I,11)-2,3*ELEMENT(I,11)-2)+KG(1,1)
		K(3*ELEMENT(I,11)-1,3*ELEMENT(I,11)-2)=K(3*ELEMENT(I,11)-1,3*ELEMENT(I,11)-2)+KG(2,1)
		K(3*ELEMENT(I,11)-0,3*ELEMENT(I,11)-2)=K(3*ELEMENT(I,11)-0,3*ELEMENT(I,11)-2)+KG(3,1)
		K(3*ELEMENT(I,12)-2,3*ELEMENT(I,11)-2)=K(3*ELEMENT(I,12)-2,3*ELEMENT(I,11)-2)+KG(4,1)
		K(3*ELEMENT(I,12)-1,3*ELEMENT(I,11)-2)=K(3*ELEMENT(I,12)-1,3*ELEMENT(I,11)-2)+KG(5,1)
		K(3*ELEMENT(I,12)-0,3*ELEMENT(I,11)-2)=K(3*ELEMENT(I,12)-0,3*ELEMENT(I,11)-2)+KG(6,1)
		!SECOND COLUMN
		K(3*ELEMENT(I,11)-2,3*ELEMENT(I,11)-1)=K(3*ELEMENT(I,11)-2,3*ELEMENT(I,11)-1)+KG(1,2)
		K(3*ELEMENT(I,11)-1,3*ELEMENT(I,11)-1)=K(3*ELEMENT(I,11)-1,3*ELEMENT(I,11)-1)+KG(2,2)
		K(3*ELEMENT(I,11)-0,3*ELEMENT(I,11)-1)=K(3*ELEMENT(I,11)-0,3*ELEMENT(I,11)-1)+KG(3,2)
		K(3*ELEMENT(I,12)-2,3*ELEMENT(I,11)-1)=K(3*ELEMENT(I,12)-2,3*ELEMENT(I,11)-1)+KG(4,2)
		K(3*ELEMENT(I,12)-1,3*ELEMENT(I,11)-1)=K(3*ELEMENT(I,12)-1,3*ELEMENT(I,11)-1)+KG(5,2)
		K(3*ELEMENT(I,12)-0,3*ELEMENT(I,11)-1)=K(3*ELEMENT(I,12)-0,3*ELEMENT(I,11)-1)+KG(6,2)
		!THIRD COLUMN
		K(3*ELEMENT(I,11)-2,3*ELEMENT(I,11)-0)=K(3*ELEMENT(I,11)-2,3*ELEMENT(I,11)-0)+KG(1,3)
		K(3*ELEMENT(I,11)-1,3*ELEMENT(I,11)-0)=K(3*ELEMENT(I,11)-1,3*ELEMENT(I,11)-0)+KG(2,3)
		K(3*ELEMENT(I,11)-0,3*ELEMENT(I,11)-0)=K(3*ELEMENT(I,11)-0,3*ELEMENT(I,11)-0)+KG(3,3)
		K(3*ELEMENT(I,12)-2,3*ELEMENT(I,11)-0)=K(3*ELEMENT(I,12)-2,3*ELEMENT(I,11)-0)+KG(4,3)
		K(3*ELEMENT(I,12)-1,3*ELEMENT(I,11)-0)=K(3*ELEMENT(I,12)-1,3*ELEMENT(I,11)-0)+KG(5,3)
		K(3*ELEMENT(I,12)-0,3*ELEMENT(I,11)-0)=K(3*ELEMENT(I,12)-0,3*ELEMENT(I,11)-0)+KG(6,3)
		!FOURTH COLUMN
		K(3*ELEMENT(I,11)-2,3*ELEMENT(I,12)-2)=K(3*ELEMENT(I,11)-2,3*ELEMENT(I,12)-2)+KG(1,4)
		K(3*ELEMENT(I,11)-1,3*ELEMENT(I,12)-2)=K(3*ELEMENT(I,11)-1,3*ELEMENT(I,12)-2)+KG(2,4)
		K(3*ELEMENT(I,11)-0,3*ELEMENT(I,12)-2)=K(3*ELEMENT(I,11)-0,3*ELEMENT(I,12)-2)+KG(3,4)
		K(3*ELEMENT(I,12)-2,3*ELEMENT(I,12)-2)=K(3*ELEMENT(I,12)-2,3*ELEMENT(I,12)-2)+KG(4,4)
		K(3*ELEMENT(I,12)-1,3*ELEMENT(I,12)-2)=K(3*ELEMENT(I,12)-1,3*ELEMENT(I,12)-2)+KG(5,4)
		K(3*ELEMENT(I,12)-0,3*ELEMENT(I,12)-2)=K(3*ELEMENT(I,12)-0,3*ELEMENT(I,12)-2)+KG(6,4)
		!FIFTH COLUMN
		K(3*ELEMENT(I,11)-2,3*ELEMENT(I,12)-1)=K(3*ELEMENT(I,11)-2,3*ELEMENT(I,12)-1)+KG(1,5)
		K(3*ELEMENT(I,11)-1,3*ELEMENT(I,12)-1)=K(3*ELEMENT(I,11)-1,3*ELEMENT(I,12)-1)+KG(2,5)
		K(3*ELEMENT(I,11)-0,3*ELEMENT(I,12)-1)=K(3*ELEMENT(I,11)-0,3*ELEMENT(I,12)-1)+KG(3,5)
		K(3*ELEMENT(I,12)-2,3*ELEMENT(I,12)-1)=K(3*ELEMENT(I,12)-2,3*ELEMENT(I,12)-1)+KG(4,5)
		K(3*ELEMENT(I,12)-1,3*ELEMENT(I,12)-1)=K(3*ELEMENT(I,12)-1,3*ELEMENT(I,12)-1)+KG(5,5)
		K(3*ELEMENT(I,12)-0,3*ELEMENT(I,12)-1)=K(3*ELEMENT(I,12)-0,3*ELEMENT(I,12)-1)+KG(6,5)
		!SIXTH COLUMN
		K(3*ELEMENT(I,11)-2,3*ELEMENT(I,12)-0)=K(3*ELEMENT(I,11)-2,3*ELEMENT(I,12)-0)+KG(1,6)
		K(3*ELEMENT(I,11)-1,3*ELEMENT(I,12)-0)=K(3*ELEMENT(I,11)-1,3*ELEMENT(I,12)-0)+KG(2,6)
		K(3*ELEMENT(I,11)-0,3*ELEMENT(I,12)-0)=K(3*ELEMENT(I,11)-0,3*ELEMENT(I,12)-0)+KG(3,6)
		K(3*ELEMENT(I,12)-2,3*ELEMENT(I,12)-0)=K(3*ELEMENT(I,12)-2,3*ELEMENT(I,12)-0)+KG(4,6)
		K(3*ELEMENT(I,12)-1,3*ELEMENT(I,12)-0)=K(3*ELEMENT(I,12)-1,3*ELEMENT(I,12)-0)+KG(5,6)
		K(3*ELEMENT(I,12)-0,3*ELEMENT(I,12)-0)=K(3*ELEMENT(I,12)-0,3*ELEMENT(I,12)-0)+KG(6,6)
	END DO
	COUNT=0
	DO I=1, 3*NUM_NODE
		IF(DOF(I)==1) COUNT=COUNT+1
	END DO
	ALLOCATE(KF(COUNT,COUNT), FEMF(COUNT),KFS(COUNT,3*NUM_NODE-COUNT),DELTAF(COUNT),DELTAS(3*NUM_NODE-COUNT),KFINV(COUNT,COUNT))
	FEM_EL=0 
!LOADING-------------------------------------------------------------------------------------------------------------------------------------
	PRINT*
	WRITE (*,*) "LOAD CASES:"
	WRITE (*,*) "1: CONCENTRATED PERPENDICULAR LOAD"
	WRITE (*,*) "2: DISTRIBUTED UNIFORM LOAD"
	WRITE (*,*) "3: WHOLE-SPAN DISTRIBUTED TRIANGULAR LOAD"
	WRITE (*,*) "4: CONCENTRATED MOMENT"
	WRITE (*,*) "5: CONCENTRATED TANGENTIAL LOAD"
	WRITE (*,*) "6: DISTRIBUTED TANGENTIAL LOAD"
	WRITE (*,*) "----------------------------------------"
	WRITE (*,104) "ENTER THE NUMBER OF LOADS:"
	READ (*,*)NUM_LOAD
	DO I=1,NUM_LOAD
		WRITE (*,104) "THE NUMBER OF ELEMENT: "
		READ (*,*) N
19		WRITE (*,100)"LOAD CASE: "
		READ (*,*) LD
		SELECT CASE (LD)
			CASE (1)
				WRITE(*,100) "LOAD MAGNITUDE? (N) "
				READ(*,*) P
				WRITE(*,100) "DISTANCE FROM THE FIRST NODE OF ELEMENT? (mm) "
				READ(*,*) AA
				L=ELEMENT(N,6)*1000
				BB=L-AA							
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-2)+0								!FIRST NODE FX
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)+(P*BB*BB*(3*AA+BB))/(L**3)	!FIRST NODE FY
				FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+1*P*BB*BB*AA/(L*L)				!FIRST NODE MOMENT	
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)+0								!SECOND NODE FX
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+(P*AA*AA*(3*BB+AA))/(L**3)	!SECOND NODE FY
				FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+(-1)*P*AA*AA*BB/(L*L)					!SECOND NODE MOMENT
				!CONVERSION TO THE GLOBAL SYSTEM
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,18)
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,18)
				!ADDITION TO OTHER FEMs
				FEM(3*ELEMENT(N,11)-2)=FEM(3*ELEMENT(N,11)-2)+FEMTEMP(3*ELEMENT(N,11)-2)			!FIRST NODE FX
				FEM(3*ELEMENT(N,11)-1)=FEM(3*ELEMENT(N,11)-1)+FEMTEMP(3*ELEMENT(N,11)-1)			!FIRST NODE FY
				FEM(3*ELEMENT(N,11))=FEM(3*ELEMENT(N,11))+FEMTEMP(3*ELEMENT(N,11))					!FIRST NODE MOMENT	
				FEM(3*ELEMENT(N,12)-2)=FEM(3*ELEMENT(N,12)-2)+FEMTEMP(3*ELEMENT(N,12)-2)			!SECOND NODE FX
				FEM(3*ELEMENT(N,12)-1)=FEM(3*ELEMENT(N,12)-1)+FEMTEMP(3*ELEMENT(N,12)-1)			!SECOND NODE FY
				FEM(3*ELEMENT(N,12))=FEM(3*ELEMENT(N,12))+FEMTEMP(3*ELEMENT(N,12))					!SECOND NODE MOMENT
				FEM_EL(1:6,N)=FEM_EL(1:6,N)+FEMTEMP(3*ELEMENT(N,11)-2:3*ELEMENT(N,12))              !NEWWWWWWWW
				FEMTEMP=0					
			CASE (2)
				WRITE(*,100) "LOAD MAGNITUDE? (N/mm) "
				READ(*,*) W
				WRITE(*,100) "LOAD LENGHT? (mm) "
				READ(*,*) D
				WRITE(*,100) "DISTANCE OF THE BEGINING OF THE LOAD FROM THE FIRST NODE OF THE ELEMENT? (mm) "
				READ(*,*) AA
				L=ELEMENT(N,6)*1000
				AA=AA+(D/2)
				BB=L-AA								
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-2)+0								!FIRST NODE FX
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)+(W*D)/(L**3)*((2*AA+L)*BB*BB+((AA-BB)*D*D)/4)		!FIRST NODE FY
				FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+1*(W*D/(L*L))*(AA*BB*BB+(AA-2*BB)*D*D/12)			!FIRST NODE MOMENT	
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)+0								!SECOND NODE FX
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+(W*D)/(L**3)*((2*BB+L)*AA*AA-((AA-BB)*D*D)/4)		!SECOND NODE FY
				FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+(-1)*(W*D/(L*L))*(AA*AA*BB+(BB-2*AA)*D*D/12)			!SECOND NODE MOMENT	
				!CONVERSION TO THE GLOBAL SYSTEM
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,18)
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,18)
				!ADDITION TO OTHER FEMs
				FEM(3*ELEMENT(N,11)-2)=FEM(3*ELEMENT(N,11)-2)+FEMTEMP(3*ELEMENT(N,11)-2)			!FIRST NODE FX
				FEM(3*ELEMENT(N,11)-1)=FEM(3*ELEMENT(N,11)-1)+FEMTEMP(3*ELEMENT(N,11)-1)			!FIRST NODE FY
				FEM(3*ELEMENT(N,11))=FEM(3*ELEMENT(N,11))+FEMTEMP(3*ELEMENT(N,11))				!FIRST NODE MOMENT	
				FEM(3*ELEMENT(N,12)-2)=FEM(3*ELEMENT(N,12)-2)+FEMTEMP(3*ELEMENT(N,12)-2)			!SECOND NODE FX
				FEM(3*ELEMENT(N,12)-1)=FEM(3*ELEMENT(N,12)-1)+FEMTEMP(3*ELEMENT(N,12)-1)			!SECOND NODE FY
				FEM(3*ELEMENT(N,12))=FEM(3*ELEMENT(N,12))+FEMTEMP(3*ELEMENT(N,12))				!SECOND NODE MOMENT
				FEM_EL(1:6,N)=FEM_EL(1:6,N)+FEMTEMP(3*ELEMENT(N,11)-2:3*ELEMENT(N,12))          !NEWWWWWWWWWW
				FEMTEMP=0					
			CASE (3)
				WRITE(*,100) "MAXIMUM MAGNITUDE OF LOAD? (N) "
				READ(*,*) W
				L=ELEMENT(N,6)*1000
20				WRITE(*,100) "IS THE ZERO PART TO THE RIGHT? <Y/N> "
				READ(*,*) VERIFY
				IF (VERIFY=="Y".OR.VERIFY=="y") THEN
					FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-2)+0							!FIRST NODE FX
					FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)+(7*W*L)/20					!FIRST NODE FY
					FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+1*W*L*L/20						!FIRST NODE MOMENT	
					FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)+0							!SECOND NODE FX
					FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+(3*W*L)/20					!SECOND NODE FY
					FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+(-1)*W*L*L/30						!SECOND NODE MOMENT			
				ELSE IF (VERIFY=="N".OR.VERIFY=="n") THEN
					FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-2)+0							!FIRST NODE FX
					FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)+(3*W*L)/20					!FIRST NODE FY
					FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+1*W*L*L/30						!FIRST NODE MOMENT	
					FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)+0							!SECOND NODE FX
					FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+(7*W*L)/20					!SECOND NODE FY
					FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+(-1)*W*L*L/20						!SECOND NODE MOMENT		
				ELSE
					GOTO 20
				END IF
				!CONVERSION TO THE GLOBAL SYSTEM
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,18)
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,18)
				!ADDITION TO OTHER FEMs
				FEM(3*ELEMENT(N,11)-2)=FEM(3*ELEMENT(N,11)-2)+FEMTEMP(3*ELEMENT(N,11)-2)			!FIRST NODE FX
				FEM(3*ELEMENT(N,11)-1)=FEM(3*ELEMENT(N,11)-1)+FEMTEMP(3*ELEMENT(N,11)-1)			!FIRST NODE FY
				FEM(3*ELEMENT(N,11))=FEM(3*ELEMENT(N,11))+FEMTEMP(3*ELEMENT(N,11))					!FIRST NODE MOMENT	
				FEM(3*ELEMENT(N,12)-2)=FEM(3*ELEMENT(N,12)-2)+FEMTEMP(3*ELEMENT(N,12)-2)			!SECOND NODE FX
				FEM(3*ELEMENT(N,12)-1)=FEM(3*ELEMENT(N,12)-1)+FEMTEMP(3*ELEMENT(N,12)-1)			!SECOND NODE FY
				FEM(3*ELEMENT(N,12))=FEM(3*ELEMENT(N,12))+FEMTEMP(3*ELEMENT(N,12))					!SECOND NODE MOMENT
				FEM_EL(1:6,N)=FEM_EL(1:6,N)+FEMTEMP(3*ELEMENT(N,11)-2:3*ELEMENT(N,12))              !NEWWWWWW
				FEMTEMP=0							
			CASE (4)
				WRITE(*,100) "MOMENT MAGNITUDE? (N.mm) (CLOCKWISE MOMENT IS CONSIDERED AS POSITIVE) "
				READ(*,*) M
				WRITE(*,100) "DISTANCE FROM THE FIRST NODE OF ELEMENT? (mm) "
				READ(*,*) AA
				L=ELEMENT(N,6)*1000
				BB=L-AA
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-2)+0								!FIRST NODE FX
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)-(2*M*AA*BB)/(L**3)			!FIRST NODE FY
				FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+(-1)*(M*BB*(2*AA-BB))/(L**2)		!FIRST NODE MOMENT	
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)+0								!SECOND NODE FX
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+(2*M*AA*BB)/(L**3)			!SECOND NODE FY
				FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+(-1)*(M*AA*(2*BB-AA))/(L**2)		!SECOND NODE MOMENT	
				!CONVERSION TO THE GLOBAL SYSTEM
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,18)
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,18)
				!ADDITION TO OTHER FEMs
				FEM(3*ELEMENT(N,11)-2)=FEM(3*ELEMENT(N,11)-2)+FEMTEMP(3*ELEMENT(N,11)-2)			!FIRST NODE FX
				FEM(3*ELEMENT(N,11)-1)=FEM(3*ELEMENT(N,11)-1)+FEMTEMP(3*ELEMENT(N,11)-1)			!FIRST NODE FY
				FEM(3*ELEMENT(N,11))=FEM(3*ELEMENT(N,11))+FEMTEMP(3*ELEMENT(N,11))					!FIRST NODE MOMENT	
				FEM(3*ELEMENT(N,12)-2)=FEM(3*ELEMENT(N,12)-2)+FEMTEMP(3*ELEMENT(N,12)-2)			!SECOND NODE FX
				FEM(3*ELEMENT(N,12)-1)=FEM(3*ELEMENT(N,12)-1)+FEMTEMP(3*ELEMENT(N,12)-1)			!SECOND NODE FY
				FEM(3*ELEMENT(N,12))=FEM(3*ELEMENT(N,12))+FEMTEMP(3*ELEMENT(N,12))				!SECOND NODE MOMENT
				FEM_EL(1:6,N)=FEM_EL(1:6,N)+FEMTEMP(3*ELEMENT(N,11)-2:3*ELEMENT(N,12))          !NEWWWWWWWW
				FEMTEMP=0					
			CASE (5)
				WRITE(*,100) "LOAD MAGNITUDE? (N) "
				READ(*,*) P
				WRITE(*,100) "LOAD DISTANCE FROM THE FIRST NODE OF THE ELEMENT? (mm) "
				READ(*,*) AA
				L=ELEMENT(N,6)*1000
				BB=L-AA	
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-2)+BB*P/L					!FIRST NODE FX
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)+0						!FIRST NODE FY
				FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+0						!FIRST NODE MOMENT	
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)+AA*P/L					!SECOND NODE FX
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+0						!SECOND NODE FY
				FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+0						!SECOND NODE MOMENT
				!CONVERSION TO THE GLOBAL SYSTEM
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,18)
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,18)
				!ADDITION TO OTHER FEMs
				FEM(3*ELEMENT(N,11)-2)=FEM(3*ELEMENT(N,11)-2)+FEMTEMP(3*ELEMENT(N,11)-2)			!FIRST NODE FX
				FEM(3*ELEMENT(N,11)-1)=FEM(3*ELEMENT(N,11)-1)+FEMTEMP(3*ELEMENT(N,11)-1)			!FIRST NODE FY
				FEM(3*ELEMENT(N,11))=FEM(3*ELEMENT(N,11))+FEMTEMP(3*ELEMENT(N,11))				!FIRST NODE MOMENT	
				FEM(3*ELEMENT(N,12)-2)=FEM(3*ELEMENT(N,12)-2)+FEMTEMP(3*ELEMENT(N,12)-2)			!SECOND NODE FX
				FEM(3*ELEMENT(N,12)-1)=FEM(3*ELEMENT(N,12)-1)+FEMTEMP(3*ELEMENT(N,12)-1)			!SECOND NODE FY
				FEM(3*ELEMENT(N,12))=FEM(3*ELEMENT(N,12))+FEMTEMP(3*ELEMENT(N,12))				!SECOND NODE MOMENT
				FEM_EL(1:6,N)=FEM_EL(1:6,N)+FEMTEMP(3*ELEMENT(N,11)-2:3*ELEMENT(N,12))          !NEWWWWWWW
				FEMTEMP=0					
			CASE (6)
				WRITE(*,100) "LOAD MAGNITUDE? (N/mm) "
				READ(*,*) W
				WRITE(*,100) "LOAD LENGHT? (mm) "
				READ(*,*) D
				WRITE(*,100) "DISTANCE OF THE BEGINING OF THE LOAD FROM THE FIRST NODE OF THE ELEMENT? (mm) "
				READ(*,*) AA
				L=ELEMENT(N,6)*1000
				AA=AA+(D/2)
				BB=L-AA-(D/2)							
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-2)+W*D*BB/L					!FIRST NODE FX
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)+0						!FIRST NODE FY
				FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+0						!FIRST NODE MOMENT	
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)+W*D*AA/L					!SECOND NODE FX
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+0						!SECOND NODE FY
				FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+0						!SECOND NODE MOMENT	
				!CONVERSION TO THE GLOBAL SYSTEM
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,18)
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,18)
				!ADDITION TO OTHER FEMs
				FEM(3*ELEMENT(N,11)-2)=FEM(3*ELEMENT(N,11)-2)+FEMTEMP(3*ELEMENT(N,11)-2)			!FIRST NODE FX
				FEM(3*ELEMENT(N,11)-1)=FEM(3*ELEMENT(N,11)-1)+FEMTEMP(3*ELEMENT(N,11)-1)			!FIRST NODE FY
				FEM(3*ELEMENT(N,11))=FEM(3*ELEMENT(N,11))+FEMTEMP(3*ELEMENT(N,11))				!FIRST NODE MOMENT	
				FEM(3*ELEMENT(N,12)-2)=FEM(3*ELEMENT(N,12)-2)+FEMTEMP(3*ELEMENT(N,12)-2)			!SECOND NODE FX
				FEM(3*ELEMENT(N,12)-1)=FEM(3*ELEMENT(N,12)-1)+FEMTEMP(3*ELEMENT(N,12)-1)			!SECOND NODE FY
				FEM(3*ELEMENT(N,12))=FEM(3*ELEMENT(N,12))+FEMTEMP(3*ELEMENT(N,12))				!SECOND NODE MOMENT
				FEM_EL(1:6,N)=FEM_EL(1:6,N)+FEMTEMP(3*ELEMENT(N,11)-2:3*ELEMENT(N,12))          !NEWWWWWWWWWWW
				FEMTEMP=0									
			CASE DEFAULT
				GOTO 19
		END SELECT
	END DO
!TEMPERATURE EFFECT--------------------------------------------------------------------------------------------------------------------------
	DO I=I,NUM_ELEM
		ELEMENT(I,6)=ELEMENT(I,6)*1000
	END DO
24	WRITE (*,104) "ARE THERE ANY TEMPERATURE EFFECTS? <Y/N> "
	READ *,VERIFY
	IF (VERIFY=="Y".OR.VERIFY=="y") THEN
		WRITE (*,104) "ENTER THE NUMBER OF ELEMENTS WITH A TEMPERATURE EFFECT: "
		READ (*,*) NUM_TEMP
		DO I=1,NUM_TEMP
			WRITE(*,104) "THE NUMBER OF THE ELEMENT? "
			READ(*,*) N
27			WRITE(*,100) "IS THE TEMPERATURE EFFECT THE UNIFORM TYPE OR THE GRADIENT TYPE? <U/G> "
			READ(*,*) VERIFY
			IF (VERIFY=="U".OR.VERIFY=="u") THEN
				WRITE (*,100) "UNIFORM TEMPERATURE CHANGE? (.C) (PAY ATTENTION TO THE POSITIVES AND NEGATIVES) "
				READ (*,*) UTEMP
				WRITE (*,100) "THERMAL EXPANSION COEFFICIENT? (1/.C) "
				READ (*,*) ALPHA
				L=ELEMENT(N,6)
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11))+ELEMENT(N,8)*ELEMENT(N,10)*ALPHA*UTEMP		!FIRST NODE FX
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)+0							!FIRST NODE FY
				FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+0							!FIRST NODE MOMENT	
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)-ELEMENT(N,8)*ELEMENT(N,10)*ALPHA*UTEMP		!SECOND NODE FX
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+0							!SECOND NODE FY
				FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+0							!SECOND NODE MOMENT	
				!CONVERSION TO THE GLOBAL SYSTEM
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,18)
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,18)
				!ADDITION TO OTHER FEMs
				FEM(3*ELEMENT(N,11)-2)=FEM(3*ELEMENT(N,11)-2)+FEMTEMP(3*ELEMENT(N,11)-2)			!FIRST NODE FX
				FEM(3*ELEMENT(N,11)-1)=FEM(3*ELEMENT(N,11)-1)+FEMTEMP(3*ELEMENT(N,11)-1)			!FIRST NODE FY
				FEM(3*ELEMENT(N,11))=FEM(3*ELEMENT(N,11))+FEMTEMP(3*ELEMENT(N,11))				!FIRST NODE MOMENT	
				FEM(3*ELEMENT(N,12)-2)=FEM(3*ELEMENT(N,12)-2)+FEMTEMP(3*ELEMENT(N,12)-2)			!SECOND NODE FX
				FEM(3*ELEMENT(N,12)-1)=FEM(3*ELEMENT(N,12)-1)+FEMTEMP(3*ELEMENT(N,12)-1)			!SECOND NODE FY
				FEM(3*ELEMENT(N,12))=FEM(3*ELEMENT(N,12))+FEMTEMP(3*ELEMENT(N,12))				!SECOND NODE MOMENT
				FEM_EL(1:6,N)=FEM_EL(1:6,N)+FEMTEMP(3*ELEMENT(N,11)-2:3*ELEMENT(N,12))          !NEWWWWWWWWW
				FEMTEMP=0													
			ELSE IF (VERIFY=="G".OR.VERIFY=="g") THEN
				WRITE (*,101) "POSITIVE= HIGHER TEMPERATURE AT THE TOP OF THE ELEMENT"
				WRITE (*,101) "NEGATIVE= HIGHER TEMPERATURE AT THE BOTTOM OF THE ELEMENT"
				WRITE (*,100) "GRADIANT TEMPERATURE CHANGE? (.C) "
				READ (*,*) GTEMP
				WRITE (*,100) "ELEMENT CROSS-SECTION HEIGHT? (mm)"
				READ (*,*) CSH
				WRITE (*,100) "THERMAL EXPANSION COEFFICIENT? (1/.C) "
				READ (*,*) ALPHA
				L=ELEMENT(N,6)
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11))+0									!FIRST NODE FX
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)+0									!FIRST NODE FY
				FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+(ELEMENT(N,8)*ELEMENT(N,9)*ALPHA*GTEMP)/CSH				!FIRST NODE MOMENT	
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)+0									!SECOND NODE FX
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+0									!SECOND NODE FY
				FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+(-1)*(ELEMENT(N,8)*ELEMENT(N,9)*ALPHA*GTEMP)/CSH				!SECOND NODE MOMENT	
				!CONVERSION TO THE GLOBAL SYSTEM
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,18)
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,18)
				!ADDITION TO OTHER FEMs
				FEM(3*ELEMENT(N,11)-2)=FEM(3*ELEMENT(N,11)-2)+FEMTEMP(3*ELEMENT(N,11)-2)			!FIRST NODE FX
				FEM(3*ELEMENT(N,11)-1)=FEM(3*ELEMENT(N,11)-1)+FEMTEMP(3*ELEMENT(N,11)-1)			!FIRST NODE FY
				FEM(3*ELEMENT(N,11))=FEM(3*ELEMENT(N,11))+FEMTEMP(3*ELEMENT(N,11))				!FIRST NODE MOMENT	
				FEM(3*ELEMENT(N,12)-2)=FEM(3*ELEMENT(N,12)-2)+FEMTEMP(3*ELEMENT(N,12)-2)			!SECOND NODE FX
				FEM(3*ELEMENT(N,12)-1)=FEM(3*ELEMENT(N,12)-1)+FEMTEMP(3*ELEMENT(N,12)-1)			!SECOND NODE FY
				FEM(3*ELEMENT(N,12))=FEM(3*ELEMENT(N,12))+FEMTEMP(3*ELEMENT(N,12))				!SECOND NODE MOMENT
				FEM_EL(1:6,N)=FEM_EL(1:6,N)+FEMTEMP(3*ELEMENT(N,11)-2:3*ELEMENT(N,12))          !NEWWWWWWWW
				FEMTEMP=0										
			ELSE
				GOTO 27
			END IF
		END DO
	ELSE IF (VERIFY=="N".OR.VERIFY=="n") THEN
		GOTO 29
	ELSE
		GOTO 24
	END IF
!SUPPORT DEFLECTION--------------------------------------------------------------------------------------------------------------------------
29	WRITE (*,104) "ARE THERE ANY SUPPORT DEFLECTIONS? <Y/N> "
	READ *, VERIFY
	IF (VERIFY=="Y".OR.VERIFY=="y") THEN
		WRITE (*,104) "ENTER THE NUMBER OF SUPPORTS WITH A DEFLECTION: "
		READ (*,*) NUM_DEF
		ALLOCATE(S_DEF(NUM_DEF,3))
		DO I=1,NUM_DEF
			WRITE(*,104) "THE NUMBER OF THE NODE WITH THE DEFLECTED SUPPORT: "
			READ(*,*) N
30				WRITE (*,100) "IS THE DEFLECTION ROTATIONAL? (NO MEANS PERPENDICULAR DEFLECTION) <Y/N> "
				READ (*,*) VERIFY
				IF (VERIFY=="N".OR.VERIFY=="n") THEN
					WRITE (*,100) "DEFLECTION (mm)? (PAY ATTENTION TO THE POSITIVES AND NEGATIVES) "
					READ (*,*) DEF
					DISP(3*N-1)=DEF
					DOF(3*N-1)=0
					S_DEF(I,1)=N
					S_DEF(I,2)=1
					S_DEF(I,3)=DEF
				ELSE IF (VERIFY=="Y".OR.VERIFY=="y") THEN
					WRITE (*,100) "DEFLECTION (RAD)? (PAY ATTENTION TO THE POSITIVES AND NEGATIVES) "
					READ (*,*) DEF
					DISP(3*N)=DEF
					DOF(3*N)=0
					S_DEF(I,1)=N
					S_DEF(I,2)=0
					S_DEF(I,3)=DEF
				ELSE
					GOTO 30	
				END IF
		END DO
	ELSE IF (VERIFY=="N".OR.VERIFY=="n") THEN
		GOTO 55
	ELSE
		GOTO 29		
	END IF	
	!SORTING OF S_DEF
55		DO II=1,NUM_DEF
			MAXX=II
			DO JJ=II+1,NUM_DEF
				IF(S_DEF(MAXX,1)<S_DEF(JJ,1)) THEN
					MAXX=JJ
					SWAPTEMP=S_DEF(MAXX,1)
					S_DEF(MAXX,1)=S_DEF(II,1)
					S_DEF(II,1)=SWAPTEMP

					SWAPTEMP=S_DEF(MAXX,2)
					S_DEF(MAXX,2)=S_DEF(II,2)
					S_DEF(II,2)=SWAPTEMP

					SWAPTEMP=S_DEF(MAXX,3)
					S_DEF(MAXX,3)=S_DEF(II,3)
					S_DEF(II,3)=SWAPTEMP
				END IF
			END DO
		END DO
!BUILD ERROR---------------------------------------------------------------------------------------------------------------------------------
41	WRITE (*,104) "ARE THERE ANY BUILD ERRORS? <Y/N> "
	READ *,VERIFY
	IF (VERIFY=="Y".OR.VERIFY=="y") THEN
		WRITE (*,104) "ENTER THE NUMBER OF ELEMENTS WITH A BUILD ERROR: "
		READ (*,*) NUM_BLD
		DO I=1,NUM_BLD
			WRITE(*,104) "THE NUMBER OF THE ELEMENT? "
			READ(*,*) N
				WRITE (*,100) "BUILD ERROR (mm)? (PAY ATTENTION TO POSITIVES AND NEGATIVES) "
				READ (*,*) BLD
				L=ELEMENT(N,6)
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11))+ELEMENT(N,8)*ELEMENT(N,10)*BLD/L				!FIRST NODE FX
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)+0								!FIRST NODE FY
				FEMTEMP(3*ELEMENT(N,11))=FEMTEMP(3*ELEMENT(N,11))+0								!FIRST NODE MOMENT	
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-2)-ELEMENT(N,8)*ELEMENT(N,10)*BLD/L				!SECOND NODE FX
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)+0								!SECOND NODE FY
				FEMTEMP(3*ELEMENT(N,12))=FEMTEMP(3*ELEMENT(N,12))+0								!SECOND NODE MOMENT	
				!CONVERSION TO THE GLOBAL SYSTEM
				FEMTEMP(3*ELEMENT(N,11)-2)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,11)-1)=FEMTEMP(3*ELEMENT(N,11)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,11)-2)*ELEMENT(N,18)
				FEMTEMP(3*ELEMENT(N,12)-2)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,18)+FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,17)
				FEMTEMP(3*ELEMENT(N,12)-1)=FEMTEMP(3*ELEMENT(N,12)-1)*ELEMENT(N,17)-FEMTEMP(3*ELEMENT(N,12)-2)*ELEMENT(N,18)
				!ADDITION TO OTHER FEMs
				FEM(3*ELEMENT(N,11)-2)=FEM(3*ELEMENT(N,11)-2)+FEMTEMP(3*ELEMENT(N,11)-2)			!FIRST NODE FX
				FEM(3*ELEMENT(N,11)-1)=FEM(3*ELEMENT(N,11)-1)+FEMTEMP(3*ELEMENT(N,11)-1)			!FIRST NODE FY
				FEM(3*ELEMENT(N,11))=FEM(3*ELEMENT(N,11))+FEMTEMP(3*ELEMENT(N,11))				!FIRST NODE MOMENT	
				FEM(3*ELEMENT(N,12)-2)=FEM(3*ELEMENT(N,12)-2)+FEMTEMP(3*ELEMENT(N,12)-2)			!SECOND NODE FX
				FEM(3*ELEMENT(N,12)-1)=FEM(3*ELEMENT(N,12)-1)+FEMTEMP(3*ELEMENT(N,12)-1)			!SECOND NODE FY
				FEM(3*ELEMENT(N,12))=FEM(3*ELEMENT(N,12))+FEMTEMP(3*ELEMENT(N,12))				!SECOND NODE MOMENT
				FEM_EL(1:6,N)=FEM_EL(1:6,N)+FEMTEMP(3*ELEMENT(N,11)-2:3*ELEMENT(N,12))          !NEWWWWWW
				FEMTEMP=0													
		END DO
	ELSE IF (VERIFY=="N".OR.VERIFY=="n") THEN
		GOTO 40
	ELSE
		GOTO 41
	END IF
!CALCULATIONS2--------------------------------------------------------------------------------------------------------------------------------
40  KF=0
	FEMF=0
	KFS=0
	DELTAF=0
	DELTAS=0
												!FORMATION OF FREE STIFFNESS MATRIX AND FREE NODES FORCES
	XX=1
	DO I=1,3*NUM_NODE
		IF(DOF(I)==1) THEN
			YY=1
				DO J=1,3*NUM_NODE
					IF(DOF(J)==1) THEN
						KF(XX,YY)=K(I,J)
						YY=YY+1
					END IF
				END DO
			FEMF(XX)=FEM(I)
			XX=XX+1
		END IF
	END DO
							!FORMATION OF FREE-SECURED STIFFNESS MATRIX
	XX=1
	DO I=1,3*NUM_NODE
		IF(DOF(I)==1) THEN
			YY=1
				DO J=1,3*NUM_NODE
					IF(DOF(J)/=1) THEN
						KFS(XX,YY)=K(I,J)
						YY=YY+1
					END IF
				END DO
			XX=XX+1
		END IF
	END DO
							!ASSEMBLAGE OF DELTA S
	XX=1
	DO I=1,3*NUM_NODE
		DO J=1,NUM_DEF
			IF(INT((3*S_DEF(J,1)-S_DEF(J,2)))==I) THEN	
				DELTAS(XX)=S_DEF(J,3)
				XX=XX+1
			ELSE IF(EOF(I)==0) THEN
				XX=XX+1
			END IF
		END DO
	END DO
CALL INVERSE(KF,KFINV,COUNT)							!INVERSE OF FREE STIFFNESS MATRIX 
	DELTAF=MATMUL(KFINV,((-1)*FEMF-MATMUL(KFS,DELTAS)))	!SOLVING THE EQUATION FOR DELTA F
	!ASSEMBLAGE OF GLOBAL DISPLACEMENT MATRIX (DELTA)
	COUNTS=1
	COUNTF=1
	DO II=1,3*NUM_NODE
		IF(DOF(II)==0) THEN
			DISP(II)=DELTAS(COUNTS)
			COUNTS=COUNTS+1
		ELSE IF(DOF(II)==1) THEN
			DISP(II)=DELTAF(COUNTF)
			COUNTF=COUNTF+1
		END IF
	END DO
	!THE FINAL ANSWERS
	FORCE=MATMUL(K,DISP)+FEM	
!OUTPUT--------------------------------------------------------------------------------------------------------------------------------------
	!NEWWWWWWWWWWWWWW(ELEMENT FORCES)
	WRITE (*,102) "OUTPUT - MOMENTS AND FORCES", "---------------------------"
	WRITE (3,102) "OUTPUT", "------"
	WRITE (*,*) "ELEMENT FORCES IN GLOBAL CO-ORDINATE SYSTEM ARE AS FOLLOWS: "
	WRITE (3,103) "ELEMENT FORCES IN GLOBAL CO-ORDINATE SYSTEM ARE AS FOLLOWS: "
	WRITE (*,*) 
	WRITE (3,*)
    DO I=1,NUM_ELEM
	    F_EL=0
		KG=0
		SCU=0
        DELTA_EL=0
		CALL KGELOBAL(ELEMENT_BACKUP(I,8),ELEMENT_BACKUP(I,9),ELEMENT_BACKUP(I,10),ELEMENT_BACKUP(I,6)*1000,COS(ELEMENT_BACKUP(I,7)),SIN(ELEMENT_BACKUP(I,7)),KG)
	    DELTA_EL(1:3)=DISP(3*ELEMENT_BACKUP(I,11)-2:3*ELEMENT_BACKUP(I,11))
		DELTA_EL(4:6)=DISP(3*ELEMENT_BACKUP(I,12)-2:3*ELEMENT_BACKUP(I,12))
		SCU(1:6)=FEM_EL(1:6,I)
		F_EL=MATMUL(KG,DELTA_EL)+SCU
	WRITE (*,106) "   ELEM NUM.", "   X-AXIS FORCE (N)", "   Y-AXIS FORCE (N)", "    MOMENT (N.mm)"
	WRITE (3,106) "   ELEM NUM.", "   X-AXIS FORCE (N)", "   Y-AXIS FORCE (N)", "    MOMENT (N.mm)"
	WRITE (*,*) "-------------------------------------------------------------------------------"
	WRITE (3,101) "-------------------------------------------------------------------------------"
	WRITE (*,*) I
	WRITE (3,*) I
    	WRITE (*,117)  F_EL(1:3)
		WRITE (3,117)  F_EL(1:3)
		WRITE (*,117)  F_EL(4:6)
		WRITE (3,117)  F_EL(4:6)
	END DO
	WRITE (3,*)
	WRITE (*,100) "PRESS RETURN TO PROCEED "
	READ *
	!NODAL DISPLACEMENTS
	WRITE (*,102) "OUTPUT - NODAL DISPLACEMENTS", "----------------------------"
	WRITE (*,*) "NODAL DISPLACEMENTS IN GLOBAL CO-ORDINATE SYSTEM ARE AS FOLLOWS: "
	WRITE (3,103) "NODAL DISPLACEMENTS IN GLOBAL CO-ORDINATE SYSTEM ARE AS FOLLOWS: "
	WRITE (3,*) 
	WRITE (*,106) "NODE NUM.", "X DISP. (mm)", "Y DISP. (mm)", "   ROTATION (RAD)"
	WRITE (3,106) "NODE NUM.", "X DISP. (mm)", "Y DISP. (mm)", "   ROTATION (RAD)"
	WRITE (*,*) "------------------------------------------------------------------------------"
	WRITE (3,101) "---------------------------------------------------------------------------"
	DO I=1,NUM_NODE
		WRITE (*,115) I, DISP(3*I-2), DISP(3*I-1), DISP(3*I-0)
		WRITE (3,115) I, DISP(3*I-2), DISP(3*I-1), DISP(3*I-0)
	END DO
	WRITE (3,101) "---------------------------------------------------------------------------"
	CLOSE(3)
	WRITE (*,100) "PRESS RETURN TO PROCEED "
	READ * 
!FORMAT SPECIFICATIONS-----------------------------------------------------------------------------------------------------------------------
100 FORMAT (X,A,X,\)										!QUESTION
101 FORMAT (X,A,X,I3,A)										!TEXT
102 FORMAT (/,X,A,/,X,A,/,X," ")
103 FORMAT (/,X,A,X,I3,A)									!RETURN+TEXT
104 FORMAT (/,X,A,X,\)										!RETURN+QUESTION
105 FORMAT (/,X,A,X,I3,A)
106 FORMAT (/,X,A,T20,A,T40,A,T60,A)						!SECTION PROPERTIES TABLE
107 FORMAT (X,F3.0,T20,ES15.4,T40,ES15.4,T60,ES15.5)		!SECTION PROPERTIES TABLE
108 FORMAT (/,X,5(A,A1))									!RETURN+USE OFASCII CODE IN THE TEXT
109 FORMAT (20(/,3X,A))										!LIST OF PEOPLE'S NAME
110 FORMAT (/,X,A1,20(A,A1))								!RETURN+ASCII
111 FORMAT (2X,A100)
112 FORMAT (58X,A30)
113 FORMAT (13(/))
114 FORMAT (X,5(A,A1))										!USE OF ASCII CODE IN THE TEXT
115 FORMAT (X,I3,T15,ES15.6,T35,ES15.6,T60,ES15.6)			!SECTION PROPERTIES TABLE
116 FORMAT (70X,A26)
117 FORMAT (X,T20,ES15.6,T40,ES15.6,T60,ES15.6)	            !NEWWWWWWWWWWWWWW
118 FORMAT (F7.3)
!GETCH---------------------------------------------------------------------------------------------------------------------------------------
	PRINT*
	PRINT*,"THE OUTPUT IS ALSO PRINTED TO OUTPUT.TXT FILE"
	WRITE (*,*) "PRESS RETURN TO TERMINATE"
	READ *
	END PROGRAM FRAME_ANALYSIS

!SUBROUTINES---------------------------------------------------------------------------------------------------------------------------------

SUBROUTINE STIFFNESS(E,I,A,L,KL)			!FORMS THE LOCAL STIFFNESS MATRIX OF A FRAME ELEMENT
	REAL E,I,A,L
	REAL, DIMENSION(6,6)::KL
	DO QQ=1,6
		DO RR=1,6
			KL(QQ,RR)=0
		END DO
	END DO
	KL(1,1)=E*A/l
	KL(4,1)=(-1)*E*A/L
	KL(2,2)=12*E*I/(L**3)
	KL(3,2)=(-6)*E*I/(L**2)
	KL(5,2)=(-12)*E*I/(L**3)
	KL(6,2)=(-6)*E*I/(L**2)
	KL(3,3)=4*E*I/L
	KL(5,3)=6*E*I/(L**2)
	KL(6,3)=2*E*I/L
	KL(4,4)=E*A/L
	KL(5,5)=12*E*I/(L**3)
	KL(6,5)=6*E*I/(L**2)
	KL(6,6)=4*E*I/L
	KL(1,4)=(-1)*E*A/L
	KL(2,3)=(-6)*E*I/(L**2)
	KL(2,5)=(-12)*E*I/(L**3)
	KL(2,6)=(-6)*E*I/(L**2)
	KL(3,5)=6*E*I/(L**2)
	KL(3,6)=2*E*I/L
	KL(5,6)=6*E*I/(L**2)
END SUBROUTINE STIFFNESS
!---------------------------------------------------------------------------------------------------------------------------------
SUBROUTINE TURN(C,S,T)					!Forms the Transposition Matrix of a frame element
	REAL C
	REAL S
	REAL , DIMENSION (6,6)::T
	DO QQ=1,6
		DO RR=1,6
			T(QQ,RR)=0
		END DO
	END DO
	T(1,1)=C
	T(2,1)=(-1)*S
	T(1,2)=S
	T(2,2)=C
	T(3,3)=1
	T(4,4)=C
	T(5,4)=(-1)*S
	T(4,5)=S
	T(5,5)=C
	T(6,6)=1
END SUBROUTINE TURN
!---------------------------------------------------------------------------------------------------------------------------------

SUBROUTINE INVERSE (MAT,INVMAT,N)       !INVERSE OF MATRIX BY GAUSS-JORDAN METHOD 
	IMPLICIT NONE
	INTEGER::N
	REAL::MAT(N,N), INVMAT(N,N), TEMPMAT(N,N)
	!LOCAL VARIABLES DECLERATIONS
	REAL::B(N,N), C, D, TEMP(N), DET
	INTEGER::I,J,K,M,IMAX(1),IPVT(N)
	TEMPMAT=MAT
	B=MAT
	IPVT=(/(I,I=1,N)/)
	DO K=1,N
		IMAX=MAXLOC(ABS(B(K:N,K)))
		M=K-1+IMAX(1)
		IF (M/=K) THEN
			IPVT((/M,K/))=IPVT((/K,M/))
			B((/M,K/),:)=B((/K,M/),:)
		END IF
		D=1/B(K,K)
		TEMP=B(:,K)
		DO J=1,N
			C=B(K,J)*D
			B(:,J)=B(:,J)-TEMP*C
			B(K,J)=C
		END DO
		B(:,K)=TEMP*(-D)
		B(K,K)=D
	END DO
	MAT(:,IPVT)=B
	INVMAT=MAT
	MAT=TEMPMAT
END SUBROUTINE INVERSE
!---------------------------------------------------------------------------------------------------------------------------------
SUBROUTINE KGELOBAL (E,I,A,L,C,S,KG)
REAL E,I,A,L,C,S
	REAL, DIMENSION(6,6)::KG
	DO QQ=1,6
		DO RR=1,6
			KG(QQ,RR)=0
		END DO
	END DO
KG(1,1)=(E*A*(C**2)/L)+(12*E*I*(S**2)/(L**3))
KG(1,2)=(E*A*C*S/L)-(12*E*I*C*S/(L**3))
KG(1,3)=(-6*E*I*S/(L**2))
KG(1,4)=((-1)*E*A*(C**2)/L)-(12*E*I*(S**2)/(L**3))
KG(1,5)=((-1)*E*A*C*S/L)+(12*E*I*C*S/(L**3))
KG(1,6)=(-6*E*I*S/(L**2))
KG(2,2)=(E*A*(S**2)/L)+(12*E*I*(C**2)/(L**3))
KG(2,3)=(6*E*I*C/(L**2))
KG(2,4)=((-1)*E*A*C*S/L)+(12*E*I*C*S/(L**3))
KG(2,5)=((-1)*E*A*(S**2)/L)-(12*E*I*(C**2)/(L**3))
KG(2,6)=(6*E*I*C/(L**2))
KG(3,3)=(4*E*I/L)
KG(3,4)=(6*E*I*S/(L**2))
KG(3,5)=(-6*E*I*C/(L**2))
KG(3,6)=(2*E*I/L)
KG(4,4)=(E*A*(C**2)/L)+(12*E*I*(S**2)/(L**3))
KG(4,5)=(E*A*C*S/L)-(12*E*I*C*S/(L**3))
KG(4,6)=(6*E*I*S/(L**2))
KG(5,5)=(E*A*(S**2)/L)+(12*E*I*(C**2)/(L**3))
KG(5,6)=(-6*E*I*C/(L**2))
KG(6,6)=(4*E*I/L)
	DO m=2,6
		Do n=1,m-1
		KG(m,n)=KG(n,m)
		END DO
	END DO
END SUBROUTINE KGELOBAL
!---------------------------------------------------------------------------------------------------------------------------------
